apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: lnkgq5mc3-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/lnkgq5mc3-java-quarkus-gitops